### ISSUE TITLE
Create of thumbview after closing previous causes errors

### ISSUE THREAD

**Issue by fire-eggs** [fire-eggs/pyTagger#21]
1. Open folder in thumbview.
2. Open second folder in thumbview.
3. Open third folder in thumbview.
4. Close 3rd view.
5. Close 2d view.
6. Open a new view. Can be same from steps 2 or 3, or new view.
7. Click on an image thumbnail.

Python error occurs. Selection doesn't happen.

**Comment by fire-eggs** [comment]
```python
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/kevin/proj/pyTagger/pyphoto/PyGadgets-source/_PyPhoto/PIL/pyphoto.py", line 846, in handler1
    singleClick(_link, imgdir, _imgfile)
  File "/home/kevin/proj/pyTagger/pyphoto/PyGadgets-source/_PyPhoto/PIL/pyphoto.py", line 720, in singleClick
    btnSelected.config(bg=orig_color, activebackground=orig_color)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1675, in configure
    return self._configure('configure', cnf, kw)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1665, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: invalid command name ".!toplevel.!scrolledcanvas.!button206"
```
